@URL=http://localhost:8080/auth

### Login
POST {{URL}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "email",
    "password": "senha"
}

### Validate Token
POST {{URL}}/validate HTTP/1.1
Authorization: Bearer {{token}}

### Refresh Token
POST {{URL}}/refresh HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "xxx",
    "username": "email"
} 